version: '3'

services:
  api-herois:
    # build: .
    image: kennedyrs/api-heroes:v1
    ports:
      - 80:3000
    environment: 
      MONGO_URL: mongo
      PORT: 3000
    depends_on: 
      - mongo
    links:
      - mongo
  
  mongo:
    image: mongo
    ports:
      - 27017:27017

